default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER", "admin") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "1234") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
development:
  primary:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB", "azaleia") %>
  cache:
    <<: *default
    database: <%= "#{ENV.fetch('POSTGRES_DB', 'azaleia')}_cache" %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: <%= "#{ENV.fetch('POSTGRES_DB', 'azaleia')}_queue" %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= "#{ENV.fetch('POSTGRES_DB', 'azaleia')}_cable" %>
    migrations_paths: db/cable_migrate
test:
  primary:
    <<: *default
    database: <%= "#{ENV.fetch('POSTGRES_DB', 'azaleia')}_test" %>
  cache:
    <<: *default
    database: <%= "#{ENV.fetch('POSTGRES_DB', 'azaleia')}_cache_test" %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: <%= "#{ENV.fetch('POSTGRES_DB', 'azaleia')}_queue_test" %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= "#{ENV.fetch('POSTGRES_DB', 'azaleia')}_cable_test" %>
    migrations_paths: db/cable_migrate
production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
    url: <%= ENV["DATABASE_URL"] %>_production_cacher
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    url: <%= ENV["DATABASE_URL"] %>_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    url: <%= ENV["DATABASE_URL"] %>_production_cable
    migrations_paths: db/cable_migrate
