default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: admin
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: localhost
  port: 5432
development:
  <<: *default
  database: azaleia
test:
  <<: *default
  database: azaleia
production:
  primary: &primary_production
    <<: *default
    database: azaleia
  cache:
    <<: *primary_production
    database: azaleia_production_cacher
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: azaleia_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: azaleia_production_cable
    migrations_paths: db/cable_migrate
